spring:
  data:
    mongodb:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
      database: reminderDb
      port: 27017
      host: localhost
  application:
    name: reminder-service
server:
  port: 8085