spring:
  data:
    mongodb:
 #     authentication-database:
 #     username: ${MONGO_USERNAME}
 #     password: ${MONGO_PASSWORD}
 #     database: ${MONGO_DATABASE}
      database: categoryDb
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083